from datetime import timedelta

RESULT_EXPIRES_TIME = timedelta(days=1)

CELERY_RESULT_EXPIRES = RESULT_EXPIRES_TIME
CELERY_BROKER_URL = 'redis://redis/4'
CELERY_RESULT_BACKEND = 'redis://redis/5'

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True

CELERY_TASK_DEFAULT_RATE_LIMIT = '10/s'
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000
CELERY_TASK_TIME_LIMIT = 1800
CELERY_WORKER_CONCURRENCY = 4
